"""The three runtime contracts that flow through a compiled graph.

These mirror the production ``multi_step_service`` framework so the format maps
1:1 onto it:

- ``ServiceState`` — the single source of truth that traverses every node.
  ``data`` persists and is visible to the agent; ``payload`` is ephemeral (the
  fields the LLM extracted *this turn*); ``internal`` persists but is hidden.
  There is **no step pointer** — position is rediscovered each turn from which
  slots in ``data`` are filled.
- ``AgentResponse`` — the contract back to the agent. ``description`` is the
  citizen-facing text / deterministic fallback; ``payload_schema`` is the JSON
  Schema handed to constrained decoding so the LLM extracts the right closed
  token next turn; ``interactive`` optionally renders buttons/list/flow.
- ``ServiceMetadata`` — autogenerated timestamps + a ``saved`` marker used by the
  empty-payload reset semantics.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class AgentResponse(BaseModel):
    """What a node hands back: a question (pause) or a result."""

    service_name: Optional[str] = None
    error_message: Optional[str] = None
    description: str = ""
    payload_schema: Optional[dict[str, Any]] = None
    data: dict[str, Any] = Field(default_factory=dict)
    # Optional signal to the tool layer to render this as a WhatsApp interactive
    # (buttons/list/flow) instead of plain text. Shape mirrors the production
    # ``AgentResponse.interactive``. ``None`` => zero effect (back-compat).
    interactive: Optional[dict[str, Any]] = None


class ServiceMetadata(BaseModel):
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: Optional[datetime] = None
    # True once the workflow has been persisted at least once. Drives the
    # empty-payload reset rule (never-saved => reset; in-progress => ignore).
    saved: bool = False

    def model_post_init(self, __context: Any) -> None:
        if self.updated_at is None:
            self.updated_at = self.created_at

    def touch(self) -> None:
        self.updated_at = _utcnow()


class ServiceState(BaseModel):
    """The single object that traverses every node of a compiled flow graph."""

    user_id: str
    service_name: str
    status: Literal["progress", "completed", "error"] = "progress"
    data: dict[str, Any] = Field(default_factory=dict)
    payload: dict[str, Any] = Field(default_factory=dict)
    internal: dict[str, Any] = Field(default_factory=dict)
    metadata: ServiceMetadata = Field(default_factory=ServiceMetadata)
    agent_response: Optional[AgentResponse] = None

    model_config = ConfigDict(arbitrary_types_allowed=True)
