"""The three runtime contracts that flow through a compiled graph.

These mirror the production ``multi_step_service`` framework so the format maps
1:1 onto it:

- ``ServiceState`` — the single source of truth that traverses every node.
  ``data`` persists and is visible to the agent; ``payload`` is ephemeral (the
  fields the LLM extracted *this turn*); ``internal`` persists but is hidden.
  There is **no step pointer** — position is rediscovered each turn from which
  slots are filled in their configured partition.
- ``AgentResponse`` — the contract back to the agent. ``description`` is the
  citizen-facing text / deterministic fallback; ``payload_schema`` is the JSON
  Schema handed to constrained decoding so the LLM extracts the right closed
  token next turn; ``interactive`` optionally renders buttons/list/flow;
  ``log_id`` correlates a warning or error with its structured log record.
- ``ServiceMetadata`` — autogenerated timestamps, persisted contract provenance,
  and a ``saved`` marker used by the empty-payload reset semantics.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Final, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr

from .clock import UtcClock, system_utc_now, utc_timestamp

CORRECTION_TARGETS_SCHEMA_KEY: Final[str] = "x-flowspec2-correction-targets"
CORRECTION_REQUESTED_INTERNAL_KEY: Final[str] = "_flowspec2_correction_requested"


class AgentResponse(BaseModel):
    """What a node hands back: a question (pause) or a result."""

    service_name: Optional[str] = None
    error_message: Optional[str] = None
    log_id: Optional[str] = Field(default=None, pattern=r"^\d+$")
    description: str = ""
    payload_schema: Optional[dict[str, Any]] = None
    data: dict[str, Any] = Field(default_factory=dict)
    # Optional signal to the tool layer to render this as a WhatsApp interactive
    # (buttons/list/flow) instead of plain text. Shape mirrors the production
    # ``AgentResponse.interactive``. ``None`` => zero effect (back-compat).
    interactive: Optional[dict[str, Any]] = None

    model_config = ConfigDict(extra="forbid")


class AwaitResumeProvenance(BaseModel):
    """Persisted identity of the external-resume contract and accepted signal."""

    step: str = Field(pattern=r"^[a-z][a-z0-9_]*$")
    version: str = Field(pattern=r"^[1-9][0-9]*(?:\.[0-9]+){0,2}$")
    digest: str = Field(pattern=r"^[0-9a-f]{64}$")
    correlation_path: str = Field(pattern=r"^\$token(?:\.[A-Za-z][A-Za-z0-9_]*)+$")
    correlation_value: Optional[StrictStr | StrictInt | StrictFloat | StrictBool] = None
    deadline: Optional[datetime] = None

    model_config = ConfigDict(extra="forbid")


class ServiceMetadata(BaseModel):
    created_at: datetime = Field(default_factory=system_utc_now)
    updated_at: Optional[datetime] = None
    flow_version: Optional[str] = None
    flow_ir_digest: Optional[str] = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    dependency_digest: Optional[str] = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    profile_digest: Optional[str] = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    await_resume: Optional[AwaitResumeProvenance] = None
    # True once the workflow has been persisted at least once. Drives the
    # empty-payload reset rule (never-saved => reset; in-progress => ignore).
    saved: bool = False

    model_config = ConfigDict(extra="forbid")

    def model_post_init(self, __context: Any) -> None:
        if self.updated_at is None:
            self.updated_at = self.created_at

    @classmethod
    def from_clock(
        cls,
        clock: UtcClock,
        *,
        flow_version: str,
        flow_ir_digest: str,
        dependency_digest: str,
        profile_digest: str,
    ) -> ServiceMetadata:
        """Create timestamped metadata bound to one resolved flow contract."""

        timestamp = utc_timestamp(clock)
        return cls(
            created_at=timestamp,
            updated_at=timestamp,
            flow_version=flow_version,
            flow_ir_digest=flow_ir_digest,
            dependency_digest=dependency_digest,
            profile_digest=profile_digest,
        )

    def touch(self, clock: UtcClock = system_utc_now) -> None:
        """Advance the update timestamp using an injectable clock."""

        self.updated_at = utc_timestamp(clock)


class ServiceState(BaseModel):
    """The single object that traverses every node of a compiled flow graph."""

    user_id: str
    service_name: str
    status: Literal["progress", "completed", "error"] = "progress"
    data: dict[str, Any] = Field(default_factory=dict)
    payload: dict[str, Any] = Field(default_factory=dict)
    internal: dict[str, Any] = Field(default_factory=dict)
    metadata: ServiceMetadata = Field(default_factory=ServiceMetadata)
    agent_response: Optional[AgentResponse] = None

    model_config = ConfigDict(arbitrary_types_allowed=True, extra="forbid")
